### ISSUE TITLE
Move to drud org as official redis recipe

### ISSUE THREAD

**Issue by rfay** [drud/ddev-redis#4]
Could we go ahead and move this repo to the drud org and make it the official redis recipe?  You would remain a maintainer.

I think you should be able to do that in the settings (and I have to accept it of course).

**Comment by hussainweb** [comment]
Hey, sorry for the delay here. I am happy to do so but when I go to do this, I see an error saying I don't have permissions to create public repos on drud organization.

**Comment by hussainweb** [comment]
@rfay I'm in the middle of a move so it might be a while before I can add you as an admin. I know it shouldn't take long and so I'll try to squeeze it in the next time I'm on my laptop.

**Comment by rfay** [comment]
It's fine, thanks!

**Comment by rfay** [comment]
Thanks for inviting me! I don't yet have adequate privs to move forward, but I think you can't set me as "owner" until after I accepted the invite, so please see if you can do that now.

**Comment by hussainweb** [comment]
I thought so too, but I don't see that option even now. I only see an option to remove access. Maybe this is because the repo is under my personal username and not an organization?

Would you be open to temporarily giving me access rights to the `ddev` organization so that I can transfer the repo there?

**Comment by rfay** [comment]
Here's what you're looking for:
<img width="887" alt="Manage_access" src="https://user-images.githubusercontent.com/112444/156066799-ed4cab74-839f-47e0-b730-56336203a06a.png">

**Comment by hussainweb** [comment]
Yes, I don't see that in this case. See the screenshot below.

![CleanShot 2022-02-28 at 22 30 28@2x](https://user-images.githubusercontent.com/1040271/156099636-9131494f-2027-496e-b88c-d97ad6c5330a.png)

I am guessing your screenshot is from an organization. I do see permissions on the orgs I manage but I don't see it in this case. I suppose you wanted to try this out with your own repo and that is why you added me there. Do you see different options in your repository?

**Comment by rfay** [comment]
I see the same issue as you on rfay/randyfay.com where you accepted my collaborator invitation - no roles. 

And I see at https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository it says 
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

So we have some ways to do this. Why don't we try a workaround. I've made you an owner of https://github.com/ddevlocal - Transfer it to that, then we'll see what we can do from there. 

If we fail at everything we can fork of course, but I'd rather move if we can pull it off.

**Comment by hussainweb** [comment]
@rfay, done. :)

**Comment by rfay** [comment]
Done, congratulations and thanks! 

Please subscribe to all notifications and continue to maintain this as you have been.
