### ISSUE TITLE
Respect the disable_settings_management flag for settings.redis.php

### ISSUE THREAD

**Issue by joelpittet** [drud/ddev-redis#6]
Thanks for adding the settings for redis!  that is a great way to get bootstrapped up with reasonable defaults.

Though sometimes it's nice to leave those up to the project! Let's respect the `disable_settings_management` flag and not add the `settings.redis.php` if that configuration is enabled.

**Comment by rfay** [comment]
Could you take a look @hussainweb ? Thanks!

**Comment by joelpittet** [comment]
I don't mind writing the PR and taking the first stab at it, just comment @hussainweb

**Comment by rfay** [comment]
Just do it! 😀

**Comment by joelpittet** [comment]
I would, just got some toddlers keeping me occupied, so need a bit more time than most, but it will be done

**Comment by joelpittet** [comment]
Ok kinda hacky about how I got the config value, a `ddev config get disable_settings_management` or something would feel less so... but added a test to the .bats file.

**Comment by joelpittet** [comment]
#7
